name: qbittorrent
description: A Helm chart for deploying simple workloads Kubernetes
annotations:
  title: qbittorrent
type: application
version: 2308.0.1
apiVersion: v2
appVersion: v1
kubeVersion: ">=1.16.0-0"
maintainers:
  - name: truenas
    url: https://www.truenas.com/
    email: dev@ixsystems.com
dependencies:
  - name: common
    repository: file://../../../common/2304.0.1
    version: 2304.0.1
home: https://www.truenas.com/
icon: https://raw.githubusercontent.com/exernest/truenas/main/img/qbittorrent.ico
keywords: []
sources: []
